apiVersion: v1
kind: Service
metadata:
  name: otus-arc-health-service
spec:
  selector:
    app: otus-arc-health
  ports:
    - protocol: TCP
      #что выставляет наружу сервис
      port: 8000
      #порт в контейнере
      targetPort: web-server
  type: NodePort

