apiVersion: batch/v1
kind: Job
metadata:
  name: "ws-user"
spec:
  template:
    metadata:
      name: "ws-user"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "pwd"
          command:
            - sh
            - "-c"
            - |
              psql postgres://postgres:pwd@pg0-postgresql/db_user <<'EOF'
                CREATE USER acdb WITH PASSWORD 'acdb';
                create sequence public.seq_object start 1;
                create table public.users (id BIGINT  not null default nextval('public.seq_object'), user_name varchar(512) null, pwd_hash varchar(512) null, first_name varchar(512) null,last_name varchar(512) null, email varchar(512) null,phone varchar(512) null, role varchar(512) not null, constraint users_pk primary key (id));
                INSERT INTO public.users (user_name, pwd_hash, first_name, last_name, role) VALUES ('admin', '{bcrypt}$2a$10$HEzgKoGmXvNqXnULyJQyA.Du5kN48A01v1KC2Muobc3FPGYsAfTtS', 'Admin', 'System', 'ROLE_ADMIN');
                create table public.event_log (id BIGINT  not null default nextval('public.seq_object'), object_id BIGINT not null, username varchar(512) null, event_type varchar(128) null,object_value varchar(512) null, moment TIMESTAMP WITH TIME ZONE not null, constraint event_log_pk primary key (id));
                create table public.orders (id BIGINT  not null default nextval('public.seq_object'), user_id BIGINT not null, idempotent_marker BIGINT null, state varchar(128) null, date_created TIMESTAMP WITH TIME ZONE not null, constraint orders_pk primary key (id));
                create table public.products (id BIGINT  not null default nextval('public.seq_object'), name varchar(512) not null, price INTEGER not null, constraint products_pk primary key (id));
                INSERT INTO public.products (name, price) VALUES ('Ancient Book', 10);
                INSERT INTO public.products (name, price) VALUES ('Piramide', 20);
                INSERT INTO public.products (name, price) VALUES ('Dragon Ball', 30);
                INSERT INTO public.products (name, price) VALUES ('Monkey', 40);
                create table public.order_detail_log (id BIGINT  not null default nextval('public.seq_object'), order_id BIGINT not null, product_id BIGINT not null, product_count INTEGER not null,is_deleted BOOLEAN not null, constraint order_detail_log_pk primary key (id));
                GRANT ALL PRIVILEGES ON public.users TO acdb;
                GRANT ALL PRIVILEGES ON public.event_log TO acdb;
                GRANT ALL PRIVILEGES ON public.orders TO acdb;
                GRANT ALL PRIVILEGES ON public.products TO acdb;
                GRANT ALL PRIVILEGES ON public.order_detail_log TO acdb;
                GRANT ALL PRIVILEGES ON public.seq_object TO acdb;
              EOF

  backoffLimit: 0