apiVersion: batch/v1
kind: Job
metadata:
  name: "ws-user"
spec:
  template:
    metadata:
      name: "ws-user"
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "passwd"
          command:
            - sh
            - "-c"
            - |
              psql postgres://myuser:passwd@myapp-postgresql/myapp <<'EOF'
                create table client (id bigint primary key, name varchar);
                insert into client (id, name) values (1, 'Konstantin');
              EOF

  backoffLimit: 0